//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStatuses
    {
        public RequestStatuses()
        {
            this.Requests = new HashSet<Requests>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
