//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public Requests()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public long id { get; set; }
        public System.DateTime StartDate { get; set; }
        public long ClimateTechTypeId { get; set; }
        public string ClimateTechModel { get; set; }
        public string ProblemDescription { get; set; }
        public long RequestStatusId { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string RepairParts { get; set; }
        public Nullable<long> MasterId { get; set; }
        public long ClientId { get; set; }
    
        public virtual ClimateTechType ClimateTechType { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual RequestStatuses RequestStatuses { get; set; }
        public virtual Users Master { get; set; }
        public virtual Users Client { get; set; }
    }
}
